volumes:
  student-volume:

services:
  db:
    image: mysql:latest
    container_name: student-crud-container_name
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studentDb
      - MYSQL_USER=studentUser
      - MYSQL_PASSWORD=studentPass
    ports:
      - "3306:3306"
    volumes:
      - student-volume:/var/lib/mysql

