volumes:
    student-volume:
services:
    db:
      image: mysql:latest
      container_name: student_container
      environment:
        - MYSQL_ROOT_PASSWORD= root
        - MYSQL_USER=studentUser
        - MYSQL_PASSWORD=studentPass
        - MYSQL_DATABASE=studentDb
      ports:
        - "3306:3306"
      volumes:
        - student-volume:/var/lib/mysql
